"""Assemble bench/REPORT.md from the benchmark JSON reports (no number is typed by hand).

Usage: python scripts/make_bench_report.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORTS = ROOT / "bench" / "reports"

TIERS = [  # (capture, label)
    ("lidar_flat", "LiDAR (iPhone 17 Pro, Stray Scanner) — blind run"),
    ("photos_v4", "Photos (iPhone 15, 1x, 5 rooms)"),
    ("video_v3", "Video (iPhone 15, walk through room centres, room mode)"),
]


def load(capture: str) -> dict | None:
    p = REPORTS / capture / f"{capture}.json"
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def fmt(v, unit="m", digits=3):
    return "—" if v is None else f"{v:.{digits}f}"


def gate_table(rep: dict) -> list[str]:
    out = ["| Item | Truth | Ours [90 % interval] | Error | Gate | Pass |", "|---|---|---|---|---|---|"]
    for r in rep["rows"]:
        if r["kind"] not in ("wall", "ceiling", "opening", "area"):
            continue
        ours = "missed" if r["ours"] is None else (
            f"{r['ours']:.3f}" + ("" if r["lo"] is None else f" [{r['lo']:.3f}, {fmt(r['hi'])}]"))
        err = "—" if r["error"] is None else (f"{r['error']:+.2f} m²" if r["kind"] == "area"
                                              else f"{r['error'] * 100:+.1f} cm")
        ok = "info" if r["passed"] is None else ("✓" if r["passed"] else "✗")
        out.append(f"| {r['key']} | {r['truth']:.3f} | {ours} | {err} | {r['gate']} | {ok} |")
    return out


def main() -> int:
    lines = ["# Benchmark report", "",
             "Generated by `scripts/make_bench_report.py` from `bench/reports/*/*.json`. Ground truth: "
             "`bench/ground_truth/flat_3bhk.yaml` (tape). Capture set: one 3BHK flat (3 bedrooms, kitchen, "
             "hall + connector) at all three tiers.", ""]
    lines += ["## Gates by tier", "", "| Tier | Walls in gate | Ceilings in gate | Median wall error | "
              "Interval coverage | Missed |", "|---|---|---|---|---|---|"]
    for cap, label in TIERS:
        rep = load(cap)
        if rep is None:
            lines.append(f"| {label} | not run | | | | |")
            continue
        s = rep["summary"]
        w, c = s["wall"], s["ceiling"]
        med = s.get("median_abs_error_pct", {}).get("wall")
        lines.append(f"| {label} | {w['passed']}/{w['total']} | {c['passed']}/{c['total']} | "
                     f"{'—' if med is None else f'{med:.2f} %'} | {s['interval_coverage']} | {s['missed']} |")
    lid = load("lidar_flat")
    if lid and lid["summary"].get("head_to_head"):
        h = lid["summary"]["head_to_head"]
        lines += ["", "## Head-to-head: LiDAR tier vs Polycam", "",
                  f"Beat or tie on **{h['beat_or_tie']}/{h['total']} = {h['rate']:.0%}** of shared dimensions "
                  f"(gate ≥ 70 %: {'PASS' if h['pass'] else 'FAIL'}). Tie = errors within 5 mm.", "",
                  "| Dimension | Tape | Ours | Our error | Polycam | Polycam error | Verdict |",
                  "|---|---|---|---|---|---|---|"]
        for r in lid["rows"]:
            if r["verdict"]:
                unit = (lambda e: f"{e:+.2f} m²") if r["kind"] == "area" else (lambda e: f"{e * 100:+.1f} cm")
                lines.append(f"| {r['key']} | {r['truth']:.3f} | {r['ours']:.3f} | {unit(r['error'])} | "
                             f"{r['app']:.3f} | {unit(r['app_error'])} | {r['verdict']} |")
    for cap, label in TIERS:
        rep = load(cap)
        if rep:
            lines += ["", f"## {label}", ""] + gate_table(rep)
    extra = ROOT / "bench" / "REPORT_extra.md"
    if extra.exists():
        lines += ["", extra.read_text(encoding="utf-8")]
    (ROOT / "bench" / "REPORT.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote bench/REPORT.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
